name: .NET Core

on:
  push:
    branches: [ master, wkrea-CICD ]
  pull_request:
    branches: [ master, malliwi88, wkrea-CICD ] # Eventos de Pull Request sobre el branch
    tags: 
      - v1.0
      - v2.0
      - v3.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207 #3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/Supermarket.API/
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/Supermarket.API/Supermarket.API.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal
